import { ChevronDown, Search } from "lucide-react";
import { Link } from "react-router-dom";
import { useState } from "react";
import type { Animal } from "@/data/animals";

export function SectionTitle({ eyebrow, title, intro }: { eyebrow?: string; title: string; intro?: string }) { return <div className="space-y-3"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-textSecondary">{eyebrow}</p><h2 className="text-3xl md:text-4xl leading-none">{title}</h2>{intro && <p className="max-w-2xl leading-7 text-textSecondary">{intro}</p>}</div>; }
export function SearchBar({ value, onChange }: { value: string; onChange: (value: string) => void }) { return <label className="flex items-center gap-3 rounded-full border border-borderLight bg-white px-5 py-4 shadow-sm focus-within:ring-1 focus-within:ring-textPrimary"><Search className="h-5 w-5 text-textSecondary" /><input value={value} onChange={(e) => onChange(e.target.value)} className="w-full bg-transparent text-base outline-none placeholder:text-textSecondary" placeholder="Search by animal, breed, or category" /></label>; }
export function CategoryFilter({ value, onChange }: { value: string; onChange: (value: string) => void }) { const categories = ["All", "Dogs", "Cats", "Birds", "Rabbits", "Horses", "Cattle", "Fish"]; return <div className="flex flex-wrap justify-center gap-2">{categories.map((category) => <button key={category} onClick={() => onChange(category)} className={`rounded-full px-4 py-2 text-sm transition-colors ${value === category ? "bg-textPrimary text-white" : "border border-borderLight text-textSecondary hover:border-textPrimary hover:text-textPrimary"}`}>{category}</button>)}</div>; }
export function AnimalCard({ animal }: { animal: Animal }) { return <article className="group flex h-full flex-col overflow-hidden rounded-2xl border border-borderLight bg-white transition duration-300 hover:-translate-y-1 hover:shadow-xl hover:shadow-black/5"><div className="aspect-[4/3] overflow-hidden"><img src={animal.image} alt={animal.name} className="h-full w-full object-cover transition duration-500 group-hover:scale-105" /></div><div className="flex flex-1 flex-col p-6"><p className="text-xs uppercase tracking-[0.16em] text-textSecondary">{animal.category}</p><h2 className="mt-3 text-3xl leading-none">{animal.name}</h2><p className="mt-2 text-sm italic text-textSecondary">{animal.scientificName}</p><p className="mt-5 flex-1 leading-7 text-textSecondary">{animal.description}</p><div className="mt-6 grid grid-cols-2 border-t border-borderLight pt-4 text-sm"><div><p className="text-textSecondary">Life span</p><p className="mt-1 font-medium">{animal.lifeSpan}</p></div><div><p className="text-textSecondary">Average weight</p><p className="mt-1 font-medium">{animal.weight}</p></div></div><Link to={`/animals/${animal.id}`} className="mt-6 text-sm font-semibold underline-offset-4 hover:underline">Learn more <span aria-hidden>→</span></Link></div></article>; }
export function FactCard({ label, value }: { label: string; value: string }) { return <div className="border-t border-borderLight py-4"><p className="text-xs uppercase tracking-[0.13em] text-textSecondary">{label}</p><p className="mt-2 text-lg">{value}</p></div>; }
export function DiseaseCard({ disease }: { disease: Animal["commonDiseases"][number] }) { return <article className="border border-borderLight p-6"><h3 className="text-2xl">{disease.name}</h3><dl className="mt-5 space-y-4 text-sm leading-6"><div><dt className="font-semibold">Symptoms</dt><dd className="text-textSecondary">{disease.symptoms}</dd></div><div><dt className="font-semibold">Prevention</dt><dd className="text-textSecondary">{disease.prevention}</dd></div></dl></article>; }
export function VaccineTimeline({ items }: { items: Animal["vaccination"] }) { return <div className="border-l border-borderLight pl-6">{items.map((item) => <div key={item.name} className="relative pb-8 last:pb-0 before:absolute before:-left-[31px] before:top-1 before:h-3 before:w-3 before:rounded-full before:border before:border-textPrimary before:bg-white"><p className="text-lg">{item.name}</p><p className="mt-1 text-sm text-textSecondary">{item.age} · {item.frequency}</p></div>)}</div>; }
export function NutritionCard({ title, items, text }: { title: string; items?: string[]; text?: string }) { return <div className="border-t border-borderLight py-5"><h3 className="text-xl">{title}</h3>{items ? <ul className="mt-3 space-y-2 text-textSecondary">{items.map((item) => <li key={item}>— {item}</li>)}</ul> : <p className="mt-3 leading-7 text-textSecondary">{text}</p>}</div>; }
export function BreedCard({ breed }: { breed: Animal["breeds"][number] }) { return <article className="min-w-[230px] overflow-hidden rounded-xl border border-borderLight"><img src={breed.image} alt={breed.name} className="aspect-[4/3] w-full object-cover" /><div className="p-4"><h3 className="text-xl">{breed.name}</h3><p className="mt-2 text-sm leading-6 text-textSecondary">{breed.description}</p></div></article>; }
export function FAQAccordion({ items }: { items: Animal["faq"] }) { const [open, setOpen] = useState<number | null>(0); return <div className="divide-y divide-borderLight border-y border-borderLight">{items.map((item, index) => <div key={item.question}><button onClick={() => setOpen(open === index ? null : index)} className="flex w-full items-center justify-between py-5 text-left text-lg"><span>{item.question}</span><ChevronDown className={`h-5 w-5 shrink-0 transition-transform ${open === index ? "rotate-180" : ""}`} /></button>{open === index && <p className="max-w-3xl pb-5 leading-7 text-textSecondary animate-fade-in">{item.answer}</p>}</div>)}</div>; }
