import { type ReactNode, useState } from "react";
import { ChevronDown, ImageOff, Search } from "lucide-react";
import { Link } from "react-router-dom";
import { cn } from "@/lib/utils";
import type { Animal } from "@/data/animals";

export function ImageWithFallback({ src, alt, className, wrapperClassName }: { src: string; alt: string; className?: string; wrapperClassName?: string }) {
  const [loaded, setLoaded] = useState(false);
  const [error, setError] = useState(false);
  return <div className={cn("relative overflow-hidden", wrapperClassName)}>{!loaded && !error && <div className="absolute inset-0 animate-pulse bg-gray-100" />}{error ? <div className="absolute inset-0 flex items-center justify-center bg-gray-50"><ImageOff className="h-6 w-6 text-gray-300" /></div> : <img src={src} alt={alt} loading="lazy" onLoad={() => setLoaded(true)} onError={() => setError(true)} className={cn(className, !loaded && "opacity-0")} />}</div>;
}

export function SectionTitle({ eyebrow, title, intro }: { eyebrow?: string; title: string; intro?: string }) { return <div className="space-y-3"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-textSecondary">{eyebrow}</p><h2 className="text-3xl md:text-4xl leading-none">{title}</h2>{intro && <p className="max-w-2xl leading-7 text-textSecondary">{intro}</p>}</div>; }
export function SearchBar({ value, onChange }: { value: string; onChange: (value: string) => void }) { return <label className="flex items-center gap-3 rounded-full border border-borderLight bg-white px-5 py-4 shadow-sm focus-within:ring-1 focus-within:ring-textPrimary"><Search className="h-5 w-5 text-textSecondary" /><input value={value} onChange={(e) => onChange(e.target.value)} className="w-full bg-transparent text-base outline-none placeholder:text-textSecondary" placeholder="Search by name, disease, or category" /></label>; }
export function CategoryFilter({ value, onChange }: { value: string; onChange: (value: string) => void }) { const categories = ["All", "Dogs", "Cats", "Birds", "Horses", "Rabbits", "Fish", "Cattle"]; return <div className="flex flex-wrap justify-center gap-2">{categories.map((category) => <button key={category} onClick={() => onChange(category)} className={`rounded-full px-4 py-2 text-sm transition-colors ${value === category ? "bg-textPrimary text-white" : "border border-borderLight text-textSecondary hover:border-textPrimary hover:text-textPrimary"}`}>{category}</button>)}</div>; }
export function AnimalCard({ animal }: { animal: Animal }) { return <article className="group flex h-full flex-col overflow-hidden rounded-2xl border border-borderLight bg-white transition duration-300 hover:-translate-y-1 hover:shadow-xl hover:shadow-black/5:shadow-black/20"><ImageWithFallback src={animal.image} alt={animal.name} wrapperClassName="aspect-[4/3]" className="h-full w-full object-cover transition duration-500 group-hover:scale-105" /><div className="flex flex-1 flex-col p-6"><p className="text-xs uppercase tracking-[0.16em] text-textSecondary">{animal.category}</p><h2 className="mt-3 text-3xl leading-none">{animal.name}</h2><p className="mt-2 text-sm italic text-textSecondary">{animal.scientificName}</p><p className="mt-5 flex-1 leading-7 text-textSecondary">{animal.description}</p><div className="mt-6 grid grid-cols-2 border-t border-borderLight pt-4 text-sm"><div><p className="text-textSecondary">Life span</p><p className="mt-1 font-medium">{animal.lifeSpan}</p></div><div><p className="text-textSecondary">Average weight</p><p className="mt-1 font-medium">{animal.weight}</p></div></div><Link to={`/animals/${animal.id}`} className="mt-6 text-sm font-semibold underline-offset-4 hover:underline">Learn more <span aria-hidden>→</span></Link></div></article>; }
export function FactCard({ label, value }: { label: string; value: string }) { return <div className="border-t border-borderLight py-4"><p className="text-xs uppercase tracking-[0.13em] text-textSecondary">{label}</p><p className="mt-2 text-lg">{value}</p></div>; }
export function DiseaseCard({ disease }: { disease: Animal["commonDiseases"][number] }) { return <article className="border border-borderLight p-6"><h3 className="text-2xl">{disease.name}</h3><dl className="mt-5 space-y-4 text-sm leading-6"><div><dt className="font-semibold">Symptoms</dt><dd className="text-textSecondary">{disease.symptoms}</dd></div><div><dt className="font-semibold">Prevention</dt><dd className="text-textSecondary">{disease.prevention}</dd></div></dl></article>; }
export function VaccineTimeline({ items }: { items: Animal["vaccination"] }) { return <div className="border-l border-borderLight pl-6">{items.map((item) => <div key={item.name} className="relative pb-8 last:pb-0 before:absolute before:-left-[31px] before:top-1 before:h-3 before:w-3 before:rounded-full before:border before:border-textPrimary before"><p className="text-lg">{item.name}</p><p className="mt-1 text-sm text-textSecondary">{item.age} · {item.frequency}</p></div>)}</div>; }
export function NutritionCard({ title, items, text }: { title: string; items?: string[]; text?: string }) { return <div className="border-t border-borderLight py-5"><h3 className="text-xl">{title}</h3>{items ? <ul className="mt-4 space-y-2 text-textSecondary">{items.map((item) => <li key={item} className="flex gap-2"><span className="mt-2 h-1 w-1 shrink-0 rounded-full bg-textSecondary" />{item}</li>)}</ul> : <p className="mt-3 leading-7 text-textSecondary">{text}</p>}</div>; }
export function BreedCard({ breed }: { breed: Animal["breeds"][number] }) { return <article className="min-w-[230px] overflow-hidden rounded-xl border border-borderLight"><ImageWithFallback src={breed.image} alt={breed.name} wrapperClassName="aspect-[4/3]" className="h-full w-full object-cover" /><div className="p-4"><h3 className="text-xl">{breed.name}</h3><p className="mt-2 text-sm leading-6 text-textSecondary">{breed.description}</p></div></article>; }
export function FAQAccordion({ items }: { items: Animal["faq"] }) { const [open, setOpen] = useState<number | null>(0); return <div className="divide-y divide-borderLight border-y border-borderLight">{items.map((item, index) => <div key={item.question}><button onClick={() => setOpen(open === index ? null : index)} className="flex w-full items-center justify-between py-5 text-left text-lg"><span>{item.question}</span><ChevronDown className={`h-5 w-5 shrink-0 transition-transform ${open === index ? "rotate-180" : ""}`} /></button>{open === index && <p className="max-w-3xl pb-5 leading-7 text-textSecondary animate-fade-in">{item.answer}</p>}</div>)}</div>; }

export function InfoList({ title, items, icon }: { title: string; items: string[]; icon?: ReactNode }) {
  return <div><h3 className="text-xl font-medium">{title}</h3><ul className="mt-4 space-y-2.5">{items.map((item) => <li key={item} className="flex gap-3 text-textSecondary leading-6"><span className="mt-0.5 shrink-0">{icon ?? "—"}</span><span>{item}</span></li>)}</ul></div>;
}

export function SymptomsCard({ symptom }: { symptom: Animal["symptomsToWatch"][number] }) {
  return <div className="border border-borderLight rounded-xl p-5"><h3 className="text-lg font-medium">{symptom.symptom}</h3><p className="mt-2 text-sm leading-6 text-textSecondary">{symptom.description}</p></div>;
}

export function EmergencyCard({ item }: { item: Animal["emergencyFirstAid"][number] }) {
  return <div className="border border-red-100 bg-red-50/50 rounded-xl p-5"><h3 className="text-base font-semibold text-red-800">{item.situation}</h3><p className="mt-2 text-sm leading-6 text-red-700">{item.action}</p></div>;
}

export function FunFactCard({ fact }: { fact: string }) {
  return <div className="border border-borderLight bg-gray-50/50 rounded-xl p-5"><p className="text-sm leading-6 text-textSecondary italic">“{fact}”</p></div>;
}
