import { useMemo, useState } from "react";
import { animals } from "@/data/animals";
import { AnimalCard, CategoryFilter, SearchBar } from "@/components/animal/AnimalComponents";

export default function Animals() {
  const [query, setQuery] = useState(""); const [category, setCategory] = useState("All"); const [page, setPage] = useState(1);
  const filtered = useMemo(() => animals.filter((animal) => (category === "All" || animal.category === category) && `${animal.name} ${animal.scientificName} ${animal.category}`.toLowerCase().includes(query.toLowerCase())), [query, category]);
  return <div className="animate-fade-in"><section className="mx-auto max-w-4xl px-6 pb-16 pt-16 text-center md:pt-24"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-textSecondary">VetiCare field notes</p><h1 className="mt-5 text-5xl leading-none md:text-7xl">Animal Encyclopedia</h1><p className="mx-auto mt-6 max-w-2xl text-lg leading-8 text-textSecondary">Learn about pet breeds, nutrition, vaccinations, common diseases, and care guides.</p><div className="mx-auto mt-10 max-w-2xl"><SearchBar value={query} onChange={(value) => { setQuery(value); setPage(1); }} /></div><div className="mt-6"><CategoryFilter value={category} onChange={(value) => { setCategory(value); setPage(1); }} /></div></section><section className="mx-auto max-w-[1280px] px-6 pb-20 md:px-12 lg:px-24"><div className="mb-8 flex items-end justify-between"><p className="text-sm text-textSecondary">{filtered.length} profiles to explore</p><p className="hidden text-sm text-textSecondary sm:block">Thoughtful care starts with understanding.</p></div>{filtered.length ? <div className="grid grid-cols-1 gap-6 md:grid-cols-2 xl:grid-cols-4">{filtered.map((animal) => <AnimalCard animal={animal} key={animal.id} />)}</div> : <div className="border-y border-borderLight py-20 text-center"><p className="text-2xl">No profiles found</p><p className="mt-3 text-textSecondary">Try a different search or category.</p></div>}<div className="mt-12 flex justify-center gap-3"><button disabled={page === 1} onClick={() => setPage(1)} className="rounded-full border border-borderLight px-5 py-2 text-sm disabled:opacity-40">Previous</button><button onClick={() => setPage(2)} className="rounded-full border border-borderLight px-5 py-2 text-sm">Next</button></div></section></div>;
}
